apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2018-12-13T18:25:30Z'
  labels:
    app: oc-votebackend-1220
  name: oc-votebackend-1220
  namespace: lin1000
  resourceVersion: '506143'
  selfLink: /api/v1/namespaces/lin1000/services/oc-votebackend-1220
  uid: 78e6564e-ff04-11e8-af4c-6af53d6223a5
spec:
  clusterIP: 172.30.56.55
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: oc-votebackend-1220
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
